language: bash

services:
  - docker

script:
  - docker build -t uudashr/jenkins-ssh-slave-docker .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push uudashr/jenkins-ssh-slave-docker;
    fi

notification:
  email:
    on_success: never
    on_failure: always
